---
galaxy_info:
  author: Doug Hellmann
  description: Configure common tools used for Python development
  license: BSD
  min_ansible_version: 1.8.2
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
  categories:
    - cloud
    - development
dependencies: []
  # List your role dependencies here, one per line. Only
  # dependencies available via galaxy should be listed here.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
  
