
<table class="table">
	<thead>
		<td>#</td>
		<td>IP</td>
		<td>Data/hora</td>
		<td>URL</td>
		<td>Metodo</td>
		<td>Protocolo</td>
	</thead>


<?php

foreach ($this->accesses as $access) {

	?>

	<tbody>
		<td><?php echo $access['id'];?></td>
		<td><?php echo $access['ipAddress'];?></td>
		<td><?php echo $access['timestamp'];?></td>
		<td><?php echo $access['pageUrl'];?></td>
		<td><?php echo $access['method'];?></td>
		<td><?php echo $access['protocol'];?></td>

		</tbody>



<?php }

 ?>


</table>

