<p><a href="<?php echo $this->url(
		array(
			'controller' => 'movie',
			'action'     => 'new'
		),
		'default',
		true) ?>">Novo Filme</a></p>


<table>
	<tr>
		<td>#</td>
		<td>Nome</td>
		<td>Genero</td>
		<td>Produtora</td>
		<td>Data</td>
	</tr>

	<?php foreach ($this->entries as $entry) { ?>
		<tr>
		<td></td>
		<td><?php echo $this->escape($entry->name) ?></td>
		<td><?php echo $this->escape($entry->genre) ?></td>
		<td><?php echo $this->escape($entry->publisher) ?></td>
		<td><?php echo $this->escape($entry->launchyear) ?></td>
		</tr>
	<?php } ?>
</table>