---
server:
    install: '1'
    packages: [vim, git, fail2ban, htop]
    timezone: America/Sao_Paulo
    locale: pt_BR.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: devenvironment, ip: 10.10.10.2, memory: '512', sharedfolder: ./, useVagrantCloud: '1', syncType: '0' }
nginx:
    install: '1'
    docroot: /vagrant/moviepedia/public
    servername: locadora.dev
mysql:
    install: '1'
    root_password: root
    database: movies
    user: movieuser
    password: 'movie123!@#'
    dump: ''
mongodb:
    install: '1'
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-mysql, php5-mongo]
python: 
    install: '1'

