---
- name: Add PyPy PPA repository
  sudo: yes
  apt_repository: repo=ppa:pypy/ppa state=present
  when: python_dev_install_pypy
- name: Install PyPy
  apt: name={{ item }} state=latest
  sudo: true
  with_items:
    - pypy
    - pypy-dev
    - python-cffi
  when: python_dev_install_pypy