<html>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<title>MoviePedia - A sua Wikipedia de filmes</title>
<style>
    body,table {
        font-family: Arial;
        font-size:14px;
    }

</style>
<body>
<div id="header"><h1>MoviePedia</h1></div>
<div id="menu"><a href="/movie">Filmes</a> | Generos | Produtores | Relatorios | SSH  </div>
<div id="content">
    <?php echo $this->layout()->content; ?>
</div>
<div><p>&nbsp;</p></div>
<div id="footer">Copyright 2016 - <a href="https://github.com/gustavoper/moviepedia">Fork me on github</a></div>
</body>
</html>
